### ISSUE TITLE
Logger crashes on Java 9

### ISSUE THREAD

**Issue by tigersoldier** [tigersoldier/JavaComp#6]
`sun.misc.SharedSecrets` is no longer available on Java 9

```
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/SharedSecrets
	at org.javacomp.logging.JLogger.findCallerStackTraceElement(JLogger.java:158)
	at org.javacomp.logging.JLogger.log(JLogger.java:148)
	at org.javacomp.logging.JLogger.fine(JLogger.java:140)
	at org.javacomp.server.io.RequestReader.fillBuffer(RequestReader.java:144)
	at org.javacomp.server.io.RequestReader.readLine(RequestReader.java:66)
	at org.javacomp.server.RequestParser.parseHeader(RequestParser.java:58)
	at org.javacomp.server.RequestParser.parse(RequestParser.java:42)
	at org.javacomp.server.RequestDispatcher.dispatchRequest(RequestDispatcher.java:62)
	at org.javacomp.server.JavaComp.run(JavaComp.java:97)
	at org.javacomp.server.JavaComp.main(JavaComp.java:239)
Caused by: java.lang.ClassNotFoundException: sun.misc.SharedSecrets
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 10 more
```

**Comment by tigersoldier** [comment]
Fixed by 0ba6c576f9d84a3e262d75559cc3e216cc3c0902
